USE masha_allah_shop;

CREATE TABLE IF NOT EXISTS users (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL, email VARCHAR(190) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL, role ENUM('admin','customer') NOT NULL DEFAULT 'customer', status ENUM('active','blocked') NOT NULL DEFAULT 'active', email_verified TINYINT(1) NOT NULL DEFAULT 0, otp_hash VARCHAR(255) NULL, otp_expires_at DATETIME NULL, otp_attempts TINYINT UNSIGNED NOT NULL DEFAULT 0, last_otp_sent_at DATETIME NULL, session_version INT UNSIGNED NOT NULL DEFAULT 1, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, INDEX idx_users_role(role), INDEX idx_users_status(status), INDEX idx_users_verified(email_verified)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS app_settings (setting_key VARCHAR(80) PRIMARY KEY, setting_value VARCHAR(255) NOT NULL) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS categories (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(80) NOT NULL UNIQUE, status ENUM('active','inactive') NOT NULL DEFAULT 'active', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS products (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, category_id INT UNSIGNED NOT NULL, name VARCHAR(140) NOT NULL, selling_price DECIMAL(10,2) NOT NULL, quantity INT NOT NULL DEFAULT 0, reorder_level INT NOT NULL DEFAULT 5, image_path VARCHAR(255) NULL, description TEXT NOT NULL, status ENUM('active','inactive') NOT NULL DEFAULT 'active', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, CONSTRAINT fk_products_category FOREIGN KEY(category_id) REFERENCES categories(id) ON DELETE RESTRICT, INDEX idx_product_category(category_id), INDEX idx_product_status(status), INDEX idx_product_reorder(quantity,reorder_level)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS services (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(120) NOT NULL, description TEXT NOT NULL, image_path VARCHAR(255) NULL, display_order INT NOT NULL DEFAULT 0, status ENUM('active','inactive') NOT NULL DEFAULT 'active', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, UNIQUE KEY uq_services_name (name)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS contact_messages (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL, email VARCHAR(190) NOT NULL, phone VARCHAR(50) NULL, subject VARCHAR(160) NOT NULL, message TEXT NOT NULL, status ENUM('new','read') NOT NULL DEFAULT 'new', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, INDEX idx_message_status(status)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS security_rate_limits (bucket_hash CHAR(64) PRIMARY KEY, attempts SMALLINT UNSIGNED NOT NULL DEFAULT 0, window_started_at DATETIME NOT NULL, blocked_until DATETIME NULL, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX idx_rate_cleanup(window_started_at,blocked_until)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS inventory_movements (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, product_id INT UNSIGNED NULL, product_name VARCHAR(140) NOT NULL, quantity_before INT NOT NULL, quantity_change INT NOT NULL, quantity_after INT NOT NULL, movement_type VARCHAR(40) NOT NULL, note VARCHAR(255) NULL, admin_user_id INT UNSIGNED NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, CONSTRAINT fk_inventory_movement_product FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE SET NULL, CONSTRAINT fk_inventory_movement_admin FOREIGN KEY(admin_user_id) REFERENCES users(id) ON DELETE SET NULL, INDEX idx_inventory_movement_product_created(product_id,created_at), INDEX idx_inventory_movement_created(created_at)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS orders (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, order_number VARCHAR(40) NOT NULL UNIQUE, customer_name VARCHAR(100) NOT NULL, customer_phone VARCHAR(50) NOT NULL, customer_email VARCHAR(190) NULL, status ENUM('new','confirmed','processing','ready','completed','cancelled') NOT NULL DEFAULT 'new', payment_status ENUM('unpaid','partial','paid','refunded') NOT NULL DEFAULT 'unpaid', payment_method ENUM('cash','easypaisa','jazzcash','bank_transfer','other') NOT NULL DEFAULT 'cash', subtotal DECIMAL(12,2) NOT NULL DEFAULT 0, discount_amount DECIMAL(12,2) NOT NULL DEFAULT 0, total_amount DECIMAL(12,2) NOT NULL DEFAULT 0, note TEXT NULL, stock_applied TINYINT(1) NOT NULL DEFAULT 0, admin_user_id INT UNSIGNED NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, CONSTRAINT fk_order_admin FOREIGN KEY(admin_user_id) REFERENCES users(id) ON DELETE SET NULL, INDEX idx_order_status_created(status,created_at), INDEX idx_order_payment_created(payment_status,created_at)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS order_items (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, order_id BIGINT UNSIGNED NOT NULL, product_id INT UNSIGNED NULL, product_name VARCHAR(140) NOT NULL, unit_price DECIMAL(12,2) NOT NULL, quantity INT UNSIGNED NOT NULL, line_total DECIMAL(12,2) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, CONSTRAINT fk_order_item_order FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE CASCADE, CONSTRAINT fk_order_item_product FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE SET NULL, INDEX idx_order_item_order(order_id), INDEX idx_order_item_product(product_id)) ENGINE=InnoDB;
INSERT IGNORE INTO categories (name) VALUES ('Cables'),('Chargers'),('Earphones'),('Speakers'),('TWS'),('Batteries'),('Repair');
INSERT IGNORE INTO services (name,description,image_path,display_order) VALUES ('Mobile Accessories','Everyday cables, chargers, earphones, batteries, speakers and more.','assets/images/service-mobile-accessories.webp',1),('Mobile Repairing','Bring your device in for a clear assessment and practical repair support.','assets/images/service-mobile-repairing.webp',2),('Mobile Software Services','Help with eligible mobile software work and device setup questions.','assets/images/service-mobile-software-services.webp',3),('EasyPaisa Services','Visit the shop for available EasyPaisa assistance and transaction services.','assets/images/service-easypaisa.webp',4),('JazzCash Services','Visit the shop for available JazzCash assistance and transaction services.','assets/images/service-jazzcash.webp',5);
