<?php
declare(strict_types=1);

$admin_title = 'Dashboard';
require __DIR__ . '/layout_top.php';
require_once __DIR__ . '/../config/email.php';
$pdo = db();
$todaySales = (float)$pdo->query("SELECT COALESCE(SUM(total_amount),0) FROM orders WHERE DATE(created_at)=CURDATE() AND status='completed' AND payment_status='paid'")->fetchColumn();
$openOrders = (int)$pdo->query("SELECT COUNT(*) FROM orders WHERE status IN ('new','confirmed','processing','ready')")->fetchColumn();
$stats = [['Products',(int)$pdo->query('SELECT COUNT(*) FROM products')->fetchColumn(),'▣'],['Total stock',(int)$pdo->query('SELECT COALESCE(SUM(quantity),0) FROM products')->fetchColumn(),'◈'],['Needs reorder',(int)$pdo->query('SELECT COUNT(*) FROM products WHERE quantity BETWEEN 1 AND reorder_level')->fetchColumn(),'!'],['Inventory value','PKR '.number_format((float)$pdo->query('SELECT COALESCE(SUM(quantity*selling_price),0) FROM products')->fetchColumn()),'₨'],['Today sales','PKR '.number_format($todaySales),'↗'],['Open orders',$openOrders,'◌']];
$messages=$pdo->query('SELECT * FROM contact_messages ORDER BY created_at DESC LIMIT 5')->fetchAll();
$low=$pdo->query('SELECT p.name,p.quantity,p.reorder_level,p.selling_price,c.name category FROM products p JOIN categories c ON c.id=p.category_id WHERE p.quantity <= p.reorder_level ORDER BY p.quantity ASC,p.name LIMIT 8')->fetchAll();
$orders=$pdo->query("SELECT order_number,customer_name,status,payment_status,total_amount,created_at FROM orders ORDER BY created_at DESC LIMIT 6")->fetchAll();
$movements=$pdo->query('SELECT m.*,COALESCE(p.name,m.product_name) product_name FROM inventory_movements m LEFT JOIN products p ON p.id=m.product_id ORDER BY m.created_at DESC LIMIT 5')->fetchAll();
$services=(int)$pdo->query("SELECT COUNT(*) FROM services WHERE status='active'")->fetchColumn(); $categories=(int)$pdo->query("SELECT COUNT(*) FROM categories WHERE status='active'")->fetchColumn(); $newMessages=(int)$pdo->query("SELECT COUNT(*) FROM contact_messages WHERE status='new'")->fetchColumn();
?>
<div class="admin-stat-grid"><?php foreach($stats as [$label,$value,$icon]):?><article class="admin-stat-card"><div class="stat-icon"><?=e($icon)?></div><strong><?=is_int($value)?number_format($value):e($value)?></strong><span><?=e($label)?></span></article><?php endforeach;?></div>
<div class="admin-content-grid"><section class="admin-panel"><div class="admin-panel-head"><h3>Recent inquiries</h3><a class="button dark" style="min-height:36px;padding:7px 12px" href="<?=url('admin/messages.php')?>">View all</a></div><?php if(!$messages):?><p class="muted">No customer inquiries yet.</p><?php else:?><div class="table-wrap"><table class="admin-table"><thead><tr><th>Customer</th><th>Subject</th><th>Status</th><th>Date</th></tr></thead><tbody><?php foreach($messages as $m):?><tr><td><strong><?=e($m['name'])?></strong><br><span class="muted"><?=e($m['email'])?></span></td><td><?=e($m['subject'])?></td><td><?=e(ucfirst($m['status']))?></td><td><?=e(date('d M, Y',strtotime($m['created_at'])))?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section><section class="admin-panel"><div class="admin-panel-head"><h3>Quick actions</h3></div><div class="quick-actions"><a class="quick-action" href="<?=url('admin/orders.php')?>"><strong>Create order</strong><span>Record a customer sale</span></a><a class="quick-action" href="<?=url('admin/orders.php')?>"><strong>Manage orders</strong><span><?=number_format($openOrders)?> open workflow items</span></a><a class="quick-action" href="<?=url('admin/inventory.php')?>"><strong>Inventory control</strong><span>Adjust stock and view audit history</span></a><a class="quick-action" href="<?=url('admin/sales.php')?>"><strong>Sales insights</strong><span>Paid revenue and top products</span></a></div></section></div>
<section class="admin-panel" style="margin-top:18px"><div class="admin-panel-head"><div><span class="eyebrow" style="color:#ae7d2c">Fulfilment</span><h3>Recent orders</h3></div><a href="<?=url('admin/orders.php')?>">Manage orders →</a></div><div class="table-wrap"><table class="admin-table"><thead><tr><th>Order</th><th>Customer</th><th>Status</th><th>Payment</th><th>Total</th></tr></thead><tbody><?php foreach($orders as $order):?><tr><td><strong><?=e($order['order_number'])?></strong><br><span class="muted"><?=e(date('d M, H:i',strtotime($order['created_at'])))?></span></td><td><?=e($order['customer_name'])?></td><td><?=e(ucfirst($order['status']))?></td><td><?=e(ucfirst($order['payment_status']))?></td><td>PKR <?=number_format((float)$order['total_amount'])?></td></tr><?php endforeach;?><?php if(!$orders):?><tr><td colspan="5" class="muted">No orders have been created yet.</td></tr><?php endif;?></tbody></table></div></section>
<section class="admin-panel" style="margin-top:18px"><div class="admin-panel-head"><div><span class="eyebrow" style="color:#ae7d2c">Priority stock</span><h3>Inventory attention</h3></div><a href="<?=url('admin/inventory.php?status=reorder')?>">Open inventory control →</a></div><?php if(!$low):?><p class="muted">All current products are above their reorder threshold.</p><?php else:?><div class="admin-alert">Review these products before stock runs out.</div><div class="table-wrap"><table class="admin-table"><thead><tr><th>Product</th><th>Category</th><th>Stock</th><th>Reorder at</th><th>Selling price</th></tr></thead><tbody><?php foreach($low as $p):?><tr><td><?=e($p['name'])?></td><td><?=e($p['category'])?></td><td><strong><?=e((string)$p['quantity'])?></strong></td><td><?=e((string)$p['reorder_level'])?></td><td>PKR <?=number_format((float)$p['selling_price'])?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section>
<section class="admin-panel" style="margin-top:18px"><div class="admin-panel-head"><div><span class="eyebrow" style="color:#ae7d2c">Stock ledger</span><h3>Recent inventory activity</h3></div><a href="<?=url('admin/inventory.php')?>">View all →</a></div><div class="table-wrap"><table class="admin-table"><thead><tr><th>Product</th><th>Change</th><th>Stock after</th><th>Note</th><th>Time</th></tr></thead><tbody><?php foreach($movements as $movement):?><tr><td><?=e($movement['product_name'])?></td><td class="<?= (int)$movement['quantity_change'] >= 0 ? 'movement-up':'movement-down'?>"><?= (int)$movement['quantity_change'] > 0 ? '+':''?><?=e((string)$movement['quantity_change'])?></td><td><?=e((string)$movement['quantity_after'])?></td><td><?=e((string)($movement['note'] ?? '—'))?></td><td><?=e(date('d M, H:i',strtotime($movement['created_at'])))?></td></tr><?php endforeach;?><?php if(!$movements):?><tr><td colspan="5" class="muted">No inventory changes are recorded yet.</td></tr><?php endif;?></tbody></table></div></section>
<section class="admin-panel" style="margin-top:18px"><div class="admin-panel-head"><h3>System snapshot</h3><span class="badge stock-in">Local / MySQL</span></div><div class="grid four"><div><strong><?=number_format($services)?></strong><div class="muted">Active services</div></div><div><strong><?=number_format($categories)?></strong><div class="muted">Active categories</div></div><div><strong><?=number_format($newMessages)?></strong><div class="muted">Unread inquiries</div></div><div><strong><?=email_configured()?'Ready':'Setup needed'?></strong><div class="muted">Email verification</div></div></div></section>
<?php require __DIR__.'/layout_bottom.php'; ?>
