<?php
declare(strict_types=1);

$admin_title = 'Sales Insights';
require __DIR__ . '/layout_top.php';
$pdo = db();

$todaySales = (float)$pdo->query("SELECT COALESCE(SUM(total_amount),0) FROM orders WHERE DATE(created_at)=CURDATE() AND status='completed' AND payment_status='paid'")->fetchColumn();
$monthSales = (float)$pdo->query("SELECT COALESCE(SUM(total_amount),0) FROM orders WHERE YEAR(created_at)=YEAR(CURDATE()) AND MONTH(created_at)=MONTH(CURDATE()) AND status='completed' AND payment_status='paid'")->fetchColumn();
$paidOrders = (int)$pdo->query("SELECT COUNT(*) FROM orders WHERE status='completed' AND payment_status='paid'")->fetchColumn();
$openOrders = (int)$pdo->query("SELECT COUNT(*) FROM orders WHERE status IN ('new','confirmed','processing','ready')")->fetchColumn();
$dailyRows = $pdo->query("SELECT DATE(created_at) day,COALESCE(SUM(total_amount),0) total FROM orders WHERE created_at >= CURDATE() - INTERVAL 6 DAY AND status='completed' AND payment_status='paid' GROUP BY DATE(created_at) ORDER BY day")->fetchAll();
$daily = []; foreach ($dailyRows as $row) $daily[$row['day']] = (float)$row['total'];
$chart = []; $max = 1.0; for ($i=6;$i>=0;$i--) { $day=date('Y-m-d',strtotime('-'.$i.' days')); $value=$daily[$day]??0.0; $chart[]=['label'=>date('D',strtotime($day)),'value'=>$value]; $max=max($max,$value); }
$topProducts = $pdo->query("SELECT oi.product_name,SUM(oi.quantity) units,SUM(oi.line_total) revenue FROM order_items oi JOIN orders o ON o.id=oi.order_id WHERE o.status='completed' AND o.payment_status='paid' GROUP BY oi.product_name ORDER BY revenue DESC,units DESC LIMIT 8")->fetchAll();
?>
<div class="sales-kpis"><article><span>Today paid sales</span><strong>PKR <?=number_format($todaySales)?></strong></article><article><span>This month</span><strong>PKR <?=number_format($monthSales)?></strong></article><article><span>Completed paid orders</span><strong><?=number_format($paidOrders)?></strong></article><article><span>Open orders</span><strong><?=number_format($openOrders)?></strong></article></div>
<div class="admin-content-grid"><section class="admin-panel"><div class="admin-panel-head"><div><span class="eyebrow" style="color:#ae7d2c">Last seven days</span><h3>Paid sales trend</h3></div></div><div class="sales-bars"><?php foreach($chart as $point):?><div class="sales-bar"><div class="sales-bar-value">PKR <?=number_format($point['value'])?></div><div class="sales-bar-track"><span style="height:<?=max(4,round(($point['value']/$max)*100))?>%"></span></div><small><?=e($point['label'])?></small></div><?php endforeach;?></div></section><section class="admin-panel"><div class="admin-panel-head"><div><span class="eyebrow" style="color:#ae7d2c">Action centre</span><h3>Sales workflow</h3></div></div><div class="quick-actions"><a class="quick-action" href="<?=url('admin/orders.php')?>"><strong>Create order</strong><span>Record a new customer sale</span></a><a class="quick-action" href="<?=url('admin/orders.php')?>"><strong>Manage orders</strong><span><?=number_format($openOrders)?> currently open</span></a><a class="quick-action" href="<?=url('admin/inventory.php')?>"><strong>Review stock</strong><span>Manage fulfilment inventory</span></a><a class="quick-action" href="<?=url('admin/products.php')?>"><strong>Update pricing</strong><span>Adjust catalogue selling prices</span></a></div></section></div>
<section class="admin-panel" style="margin-top:18px"><div class="admin-panel-head"><div><span class="eyebrow" style="color:#ae7d2c">Performance</span><h3>Top paid products</h3></div><a href="<?=url('admin/orders.php')?>">Open orders →</a></div><div class="table-wrap"><table class="admin-table"><thead><tr><th>Product</th><th>Units sold</th><th>Paid revenue</th></tr></thead><tbody><?php foreach($topProducts as $product):?><tr><td><strong><?=e($product['product_name'])?></strong></td><td><?=number_format((int)$product['units'])?></td><td>PKR <?=number_format((float)$product['revenue'])?></td></tr><?php endforeach;?><?php if(!$topProducts):?><tr><td colspan="3" class="muted">Complete and mark an order as paid to start building sales insights.</td></tr><?php endif;?></tbody></table></div></section>
<?php require __DIR__ . '/layout_bottom.php'; ?>
